added lots more code

diff --git a/resource/out b/resource/out
--- a/resource/out
+++ b/resource/out
@@ -18,15 +18,89 @@ payload=$(mktemp "$TMPDIR/resource-request.XXXXXX")
 cat > "$payload" <&0
 
 #from the task
-org=$(jq -r '.params.org // ""' < "$payload")
-space=$(jq -r '.params.space // ""' < "$payload")
-current_app_name=$(jq -r '.params.current_app_name // ""' < "$payload")
-manifest_file=$(jq -r '.params.manifest // ""' < "$payload")
-manifest=/tmp/build/put/$manifest_file
-path_file=$(jq -r '.params.path // ""' < "$payload")
-path=/tmp/build/put/$path_file
-show_app_log=
-no_start=$(jq -r '.params.no_start // ""' < "$payload")
+org=$(jq -r '.params.org // ""' < "$payload") #required
+space=$(jq -r '.params.space // ""' < "$payload") #required
+current_app_name=$(jq -r '.params.current_app_name // ""' < "$payload") #required
+
+
+path_file=$(jq -r '.params.path // ""' < "$payload") #optional
+if [ -z ${path_file+x} ]
+  then
+    path=
+  else
+    path=/tmp/build/put/$path_file
+fi
+
+manifest_file_location=$(jq -r '.params.manifest // ""' < "$payload") #required
+manifest=/tmp/build/put/$manifest_file_location
+###
+
+
+##############################################################
+#get and set manifest variables
+manifest_env_variables_json=$(jq -r '.params.manifest_env_variables // ""' < "$payload")
+if [[ ! -z ${manifest_env_variables_json+x} ]]
+  then   #append these variables to the manifest yml file under env:
+    #eval $( echo $manifest_env_variables_json | jq -r 'to_entries | .[] | .key + "=\"" + .value + "\""')
+  get_keys() {
+    echo "$manifest_env_variables_json" | jq -r 'keys[]'
+  }
+
+  get_value() {
+    local key=${1:?key null or not set}
+    echo "$manifest_env_variables_json" | jq -r --arg key "$key" '.[$key]'
+  }
+
+  has_app_name() {
+    [ -n "$current_app_name" ] && [ -n "$(yq read "$manifest" "applications.name==$current_app_name")" ]
+  }
+
+  has_one_app() {
+    [ "1" == "$(yq read "$manifest" "applications" -l)" ]
+  }
+
+  for key in $(get_keys); do
+    if has_app_name; then
+      yq write -i "$manifest" -- "applications(name==$current_app_name).env.$key" "$(get_value "$key")"
+    elif has_one_app; then
+      yq write -i "$manifest" -- "applications[0].env.$key" "$(get_value "$key")"
+    else
+      yq write -i "$manifest" -- "env.$key" "$(get_value "$key")"
+    fi
+  done
+
+
+fi
+
+##############################################################
+
+smoketest_file=$(jq -r '.params.smoketest // ""' < "$payload") #optional
+if [ -z ${smoketest_file+x} ]
+  then
+    smoketest=
+  else
+    smoketest=/tmp/build/put/$smoketest_file
+    ## load in params, if any
+      smoketest_vars_json=$(jq -r '.params.smoketest_variables // ""' < "$payload")
+      if [[ ! -z ${smoketest_variables+x} ]]
+        then   #set all those params as actual
+         eval $( echo $smoketest_vars_json | jq -r 'to_entries | .[] | .key + "=\"" + .value + "\""')
+      fi
+    # jq '.key' <<< "$json_data"
+
+fi
+
+no_start=$(jq -r '.params.no_start // ""' < "$payload") #optional
+if [$no_start==true]
+    then
+     no_start_option=" --no-start"
+    else
+     no_start_option=""
+fi
+
+
+keep_old_app=$(jq -r '.params.keep_old_app // ""' < "$payload") #optional
+
 
 #from the resource
 api=$(jq -r '.source.api // ""' < "$payload")
@@ -41,6 +115,10 @@ if [$skip_cert_check==true]
     skipssl=""
 fi
 
+
+
+
+
 ## to test in the hijacked container:
     #.source. is from resource  
     #.params. is from task
@@ -49,12 +127,8 @@ fi
 ## cat resource-request.RANDOMWHATEVER | jq -r '.[]'
 ## cat resource-request.RANDOMWHATEVER | jq -r '.source.username // ""'
 
-echo "setting api"  >&2
-cf api "$api"
-echo "success" >&2
-
 echo "logging in"  >&2
-cf login -u "$username" -p "$password" "$skipssl"
+cf login -a "$api" -u "$username" -p "$password" $skipssl
 echo "success" >&2
 
 echo "setting target"  >&2
@@ -74,32 +148,11 @@ echo "Renaming $current_app_name to $blue_app_name"  >&2
 cf rename "$current_app_name" "$blue_app_name"
 echo "success" >&2
 
-##set up variable for the new app name
+##set up a few variables
 green_app_name="green-$current_app_name"
-
-
-
-
-
-
-
-# # . Generate random route
-# # ** Need to write something for this, remembering the domain name cannot be more than 63 characters
-
-###############
-    ##get the domain from the input
-#domain=$(get_option '.domain')
 original_route=$(cf app $blue_app_name | grep routes | awk '{print $2}')
 original_hostname="$(cut -d '.' -f 1 <<< "$original_route" )"
 original_domain="$(cut -d '.' -f 2- <<< "$original_route" )"
-## echo $original_route
-## echo $original_hostname
-## echo $original_domain
-
- #hostname=$(get_option '.hostname')
-    ## new route will be $green_app_name.$original_domain
-###############
-# begin setting up args for new route
 
 #new temporary green hosthame:
 green_hostname=green-$original_hostname
@@ -113,10 +166,8 @@ echo "Creating new temporary route of $green_route_path..."  >&2
 cf create-route $space $original_domain --hostname $green_hostname
 echo "success" >&2
 
-#fly -t main-lab-ops hijack -j bluegreen-test-config-server-pipeline/deploy-sandbox
-
 echo "Pushing new green app $green_app_name with no route."  >&2
-cf push $green_app_name -f $manifest -p $path --no-route
+cf push $green_app_name -f $manifest -p $path --no-route $no_start_option
 echo "success" >&2
 
 #map green app to green route
@@ -124,34 +175,55 @@ echo "Mapping green app $green_app_name to $green_route_path"  >&2
 cf map-route $green_app_name $original_domain -n $green_hostname
 echo "success" >&2
 
-#if show_app_log then cf logs "$app_name" --recent
-#cf logs "$green_app_name" --recent
 
-# . Push green app with random route 
-##cf push sets domain as default apps.internal, subdomain.example.com
-## https://cli.cloudfoundry.org/en-US/v6/push.html
+######################################SMOKE TEST######################################
 
 
+if [ -z ${smoketest+x} ]
+ then 
+    echo "Smoketesting skipped." >&2
+  else 
+    echo "Beginning smoketest: $smoketest"  >&2
 
-#https://cli.cloudfoundry.org/en-US/v6/push.html
-#include the new random route in this push 
-
-
-#execute smoke tests, if any
-# . For each smoke test
-# .. Execute passing in the random route as the first input (`$1`)
-# .. Capture the result
-# *** If `exit_code` is 0, continue
-# *** Else
-# **** If `clean_up` is `true`
-# ***** Delete green
-# ***** Rename blue by removing prefix `blue-`
-# **** `exit 1`
+#setting smoketest url for green app
+SMOKETEST_URL="https://$green_hostname.$original_domain"
 
 
+chmod +x $smoketest  #set the script to executable
+TEST=$($smoketest) #runs the test
+STATUS=$? #gets the exit code/last executed cmd from the test
+    if [ $STATUS -eq 0 ]  # report back on smoketest
+      then 
+          echo "Smoketest successfully passed!"  >&2
+      else 
+          echo "Smoketest failed."  >&2
+          echo "Running cleanup..."  >&2
+          cleanup_if_errors()
+    fi
 
-#if success from smoke test (or no smoke tests offered)
-echo "...Smoke tests would go here, if we did that...."  >&2
+fi
+
+cleanup_if_errors(){
+    # . Rename blue app to the original app name
+  echo "Renaming blue app to the original app name"  >&2
+  cf rename $blue_app_name $current_app_name
+  echo "success" >&2
+
+  # . delete the unused green route
+  echo "Delete green route"  >&2
+  cf delete-route $original_domain -n $green_hostname
+  echo "success" >&2
+
+  #. Delete green
+  echo "Deleting app $green_app_name"  >&2
+  cf delete $green_app_name -f
+  echo "success" >&2
+
+  exit 1
+
+}
+######################################################################################
+
 
 # . Map route from incoming manifest to green
 echo "Mapping original route to green app"  >&2
@@ -179,33 +251,25 @@ echo "Renaming green app to the original app name"  >&2
 cf rename $green_app_name $current_app_name
 echo "success" >&2
 
-##IF CLEANUP IS TRUE
-
-#. Delete blue
-echo "Deleting app $blue_app_name"  >&2
-cf delete $blue_app_name -f
-echo "success" >&2
-
 echo "Deleting green route "  >&2
 cf delete-route $original_domain -n $green_hostname -f
 echo "success" >&2
 
-# OR rename it, so it can be looked at later,
-#cf rename $blue_app_name $current_app_name-old
 
+##IF CLEANUP IS TRUE  (gotta write this part)
 
-
-
-
-
-
-
-
-
-
-
-
-
+if [$keep_old_app==true]
+    then
+    #delete blue
+      echo "Deleting app $blue_app_name"  >&2
+      cf delete $blue_app_name -f
+      echo "success" >&2
+    else
+    #rename blue
+      echo "Renaming app $blue_app_name to $current_app_name-old"  >&2
+      cf rename $blue_app_name $current_app_name-old  
+      echo "success" >&2
+fi
 
 
 ##done
