more features

diff --git a/resource/out b/resource/out
--- a/resource/out
+++ b/resource/out
@@ -5,10 +5,11 @@ set -e -u
 exec 3>&1 # make stdout available as fd 3 for the result
 exec 1>&2 # redirect all output to stderr for logging
 
-BRed='\033[1;31m'   #Bold red
-BGreen='\033[1;32m' # Bold Green
-BBlue='\033[1;34m'  # Bold Blue
-NC='\033[0m'        # No Color
+BRed='\033[1;31m'    # Bold red
+BGreen='\033[1;32m'  # Bold Green
+BBlue='\033[1;34m'   # Bold Blue
+BYellow='\033[1;33m' # Bold Yellow
+NC='\033[0m'         # No Color
 
 source=$1
 if [[ -z "$source" ]]; then
@@ -27,15 +28,25 @@ org=$(jq -r '.params.org // ""' <"$payload")                           #required
 space=$(jq -r '.params.space // ""' <"$payload")                       #required
 current_app_name=$(jq -r '.params.current_app_name // ""' <"$payload") #required
 
-path_file=$(jq -r '.params.path // ""' <"$payload") #optional
-if [ -z ${path_file+x} ]; then
-  path=
-else
-  path=/tmp/build/put/$path_file
-fi
+
 
 manifest_file_location=$(jq -r '.params.manifest // ""' <"$payload") #required
 manifest=/tmp/build/put/$manifest_file_location
+
+
+path_file=$(jq -r '.params.path // ""' <"$payload") #required to be in either the params OR read from the manifest
+if [[ -z ${path_file+x} ]]; then
+  path=/tmp/build/put/$path_file
+else
+  path=$(yq read "$manifest" "applications.name==$current_app_name.path") 
+fi
+
+##exit if the path wasn't set from the pipeline nor the manifest
+if [[ -z $path ]]; then
+echo "Path must be specified in the pipeline or in the manifest."
+exit 1
+fi
+
 ###
 
 ##############################################################
@@ -88,13 +99,6 @@ if [[ ! -z ${smoketest_file+x} ]]; then
   fi
 fi
 
-no_start=$(jq -r '.params.no_start // ""' <"$payload") #optional
-if [[ -n "$no_start" ]] && [[ $no_start==true ]]; then
-  no_start_option=" --no-start"
-else
-  no_start_option=""
-fi
-
 keep_old_app=$(jq -r '.params.keep_old_app // ""' <"$payload") #optional
 
 #from the resource
@@ -109,14 +113,6 @@ else
   skipssl=""
 fi
 
-## to test in the hijacked container:
-#.source. is from resource
-#.params. is from task
-
-## cd /tmp/bluegreen | ls
-## cat resource-request.RANDOMWHATEVER | jq -r '.[]'
-## cat resource-request.RANDOMWHATEVER | jq -r '.source.username // ""'
-
 printf "${BBlue}logging in${NC}\n" >&2
 cf login -a "$api" -u "$username" -p "$password" $skipssl
 printf "${BGreen}Successful.${NC}\n" >&2
@@ -129,18 +125,63 @@ printf "${BGreen}Successful.${NC}\n" >&2
 if [[ $(cf apps | grep $current_app_name) ]]; then
   printf "${BBlue}$current_app_name found. Proceeding with Blue Green Deployment${NC}\n" >&2
 else
-  printf "${BRed}$current_app_name not found. Exiting.${NC}\n" >&2
-  exit 1
+  ########## new app with new route ###########
+  printf "${BRed}$current_app_name not found.${NC}\n" >&2
+  printf "${BYellow}$current_app_name will be deployed.${NC}\n" >&2
+
+  ##check if hostname & domain were set.
+  if [[ ! -n "$new_hostname" ]] && [[ ! -n "$new_domain" ]]; then
+    printf "${BRed}Domain and hostname must be specified for new deployments.${NC}\n" >&2
+    exit 1
+  fi
+
+  ##Pull route from the manifest.
+  if [ yq read "$manifest" "applications.name==$current_app_name.routes" -l == 1 ]; then
+    manifest_route=$(yq read "$manifest" "applications.name==$current_app_name.routes[0].route")
+  else
+    printf "${BRed}This concourse resource_type can only handle one route as provided by the manifest.${NC}\n" >&2
+    exit 1
+  fi
+  new_hostname="$(cut -d '.' -f 1 <<<"$manifest_route")"
+  new_domain="$(cut -d '.' -f 2- <<<"$manifest_route")"
+
+  printf "${BBlue}Creating new route of $new_route_path...${NC}\n" >&2
+  cf create-route $space $new_domain --hostname $new_hostname
+  printf "${BGreen}Successful.${NC}\n" >&2
+
+  printf "${BBlue}Pushing new app $current_app_name with no route.${NC}\n" >&2
+  cf push $current_app_name -f $manifest -p $path --no-route
+  printf "${BGreen}Successful.${NC}\n" >&2
+
+  #map green app to green route
+  printf "${BBlue}Mapping app $current_app_name to $new_route_path${NC}\n" >&2
+  cf map-route $current_app_name $new_domain -n $new_hostname
+  printf "${BGreen}Successful.${NC}\n" >&2
+
+  printf "${BGreen}Fresh deploy of $current_app_name completed. (No smoketesting completed at this time.)${NC}\n" >&2
+
+  exit 0
+#######################################
 fi
 
 ## rename current_app_name to blue
 blue_app_name="blue-$current_app_name"
+
+#check if blue exists, delete it if so.. then continue
+if [[ $(cf apps | grep $blue_app_name) ]]; then
+  printf "${BBlue}Older $blue_app_name found. Removing this app before continuing.${NC}\n" >&2
+  cf delete $blue_app_name -f
+  printf "${BGreen}Successful.${NC}\n" >&2
+fi
+
 printf "${BBlue}Renaming $current_app_name to $blue_app_name ${NC}\n" >&2
 cf rename "$current_app_name" "$blue_app_name"
 printf "${BGreen}Successful.${NC}\n" >&2
 
 ##set up a few variables
 green_app_name="green-$current_app_name"
+
+## Use route currently in use.
 original_route=$(cf app $blue_app_name | grep routes | awk '{print $2}')
 original_hostname="$(cut -d '.' -f 1 <<<"$original_route")"
 original_domain="$(cut -d '.' -f 2- <<<"$original_route")"
@@ -155,8 +196,15 @@ printf "${BBlue}Creating new temporary route of $green_route_path...${NC}\n" >&2
 cf create-route $space $original_domain --hostname $green_hostname
 printf "${BGreen}Successful.${NC}\n" >&2
 
+#check if green exists, delete it if so.. then continue
+if [[ $(cf apps | grep $green_app_name) ]]; then
+  printf "${BBlue}Older $green_app_name found. Removing this app before continuing.${NC}\n" >&2
+  cf delete $green_app_name -f
+  printf "${BGreen}Successful.${NC}\n" >&2
+fi
+
 printf "${BBlue}Pushing new green app $green_app_name with no route.${NC}\n" >&2
-cf push $green_app_name -f $manifest -p $path --no-route $no_start_option
+cf push $green_app_name -f $manifest -p $path --no-route
 printf "${BGreen}Successful.${NC}\n" >&2
 
 #map green app to green route
@@ -167,9 +215,10 @@ printf "${BGreen}Successful.${NC}\n" >&2
 ######################################SMOKE TEST######################################
 
 if [ -z ${smoketest+x} ]; then
+  printf "${BYellow}Smoketest script not specified in pipeline.${NC}\n" >&2
   printf "${BBlue}Smoketesting skipped.${NC}\n" >&2
 else
-  printf "${BBlue}Beginning smoketest: full location: $smoketest  file: $smoketest_file${NC}\n" >&2
+  printf "${BYellow}Beginning smoketest: $smoketest_file${NC}\n" >&2
 
   #setting smoketest url for green app
   SMOKETEST_URL="https://$green_hostname.$original_domain"
@@ -180,8 +229,9 @@ else
   if [ $STATUS -eq 0 ]; then # report back on smoketest
     printf "${BGreen}Smoketest successfully passed!${NC}\n" >&2
   else
-    echo "Smoketest failed." >&2
-    echo "Running cleanup..." >&2
+    printf "${BRed}Smoketest failed!${NC}\n" >&2
+    printf "${BRed}Running cleanup...${NC}\n" >&2
+
     # . Rename blue app to the original app name
     printf "${BBlue}Renaming blue app to the original app name${NC}\n" >&2
     cf rename $blue_app_name $current_app_name
@@ -229,7 +279,6 @@ printf "${BBlue}Renaming green app to the original app name${NC}\n" >&2
 cf rename $green_app_name $current_app_name
 printf "${BGreen}Successful.${NC}\n" >&2
 
-
 #######If keep old app is true...
 
 if [[ -n "$keep_old_app" ]] && [[ $keep_old_app==true ]]; then
@@ -243,7 +292,7 @@ if [[ -n "$keep_old_app" ]] && [[ $keep_old_app==true ]]; then
   printf "${BGreen}Successful.${NC}\n" >&2
 else
   #delete blue
-  printf "${BBlue}Deleting app $blue_app_name${NC}\n" >&2
+  printf "${BBlue}Deleting old app $blue_app_name${NC}\n" >&2
   cf delete $blue_app_name -f
   printf "${BGreen}Successful.${NC}\n" >&2
 fi
